version: '3.8'

services:
  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://127.0.0.1:5432/FancyQuizzesDb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=3312
    volumes:
      - ./secrets:/secrets